name: Brand Nudge CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      POPULATE_DB: ${{ secrets.POPULATE_DB }}
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
      - uses: actions/checkout@v3
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
